from classes.follow import Follow
from helper import set_debug

follow = Follow("green", True)
set_debug(True)

left = follow.read_raw("middle")
middle = follow.read_raw("middle")
right = follow.read_raw("right")
print(f"left: {left}, middle: {middle}, right: {right}")


# print("\t Testing left sensor")
# print("---------------------")
# left = follow.debug_color_reading("left")
# print("left finished")
# print("other sensor readings")
# print("middle")
# middle = follow.debug_color_reading("middle")
# print("right")
# right = follow.debug_color_reading("right")
# follow._safe_input()
# print("\t Testing middle sensor")
# print("---------------------")
# middle = follow.debug_color_reading("middle")
# print("middle finished")
# print("other sensor readings")
# print("middle")
# middle = follow.debug_color_reading("middle")
# print("right")
# right = follow.debug_color_reading("right")
# follow._safe_input()
# print("\t Testing right sensor")
# print("---------------------")
# right = follow.debug_color_reading("right")
# print("right finished")
# print("other sensor readings")
# print("middle")
# middle = follow.debug_color_reading("middle")
# print("right")
# right = follow.debug_color_reading("right")
